#!/usr/bin/env bash
#
# gen-skills.sh - write the kit's skills (skills/<name>/SKILL.md) from the doctrine. Never by hand.
#
# The problem it solves: a skill is the first text an agent reads, and the kit's rules live in AGENTS.md and
# doctrine/NEXT.md. A skill written by hand is a second copy of them, and copies drift: a fork that copied an 8,400-
# character "constitution" into nine skills lost about ten rules on the way and was already stale a week later; and a
# skill that carried the whole constitution was read around, not invoked. So each SKILL.md here is thin, and every
# sentence in it that states a rule is EXTRACTED from the doctrine when this script runs:
#   - the six rules every skill carries: the block between `<!-- invariants:begin -->` and `<!-- invariants:end -->`
#     in AGENTS.md, byte for byte, markers included;
#   - "This phase": the NEXT.md rows the skill owns, each with its "do this" cell, read from the table by id;
#   - "Gate": the phase's cell of AGENTS.md section 3;
#   - "Read on entry": the path, and AGENTS.md section 7's own line for it when it has one;
#   - the entry skill's four steps: sentences of AGENTS.md, each checked to be there before it is written;
#   - the doctor's checks: each script's own first line (line 3 of its header).
# What is NOT extracted is short and kept as DATA below: which skill owns which rows, the trigger words of each
# description, and the "Read on entry" / "Read when" lists. The only prose this script adds is structure: headings,
# the labels of the entry skill's steps, the "Everything else is in AGENTS.md" line and the "Done when" line.
# Paths: every file a skill names is written `{{KIT}}/<path>`, <path> from the kit's root; a path inside a cell or a
# sentence taken from the doctrine (`scripts/battery.sh`, `JUDGES.md`) gets the same prefix when it names a file of the
# kit (at the root, or a bare name under doctrine/), and is left alone otherwise (`pending/<id>.t.sol`, `STATE.md`).
# `{{KIT}}` is replaced by scripts/install-skills.sh with where the kit is, seen from the project (default
# lib/hook-gauntlet). scripts/skills-check.sh regenerates into a temporary directory and compares: drift is red.
#
# The design (thin skills, the row -> skill table, the per-phase shape This phase / Gate / Read on entry / Read when /
# Done when, the entry skill's four steps) is Pedro Santana's, from his fork of this kit that turned it into skills
# (0xZ0uk/hook-gauntlet, 2026-09); what changed is that nothing in a skill is written by hand.
#
# Usage:   scripts/gen-skills.sh [--out DIR]
#   --out DIR   where to write <name>/SKILL.md (default: the kit's skills/). A <name>/SKILL.md that is there and was not
#               written by this script (no "generated by" line) is refused, never overwritten.
# Output:  "wrote <name>/SKILL.md (<bytes> bytes, <lines> lines)" per skill, then "gen-skills: <n> skills written to <DIR>".
# Exit:    0 written; 2 REFUSED - AGENTS.md's invariants markers are not one begin then one end, a row of NEXT.md's
#          table no skill owns (or a row owned that the table does not have), a phase with no gate cell, a sentence
#          quoted here that AGENTS.md no longer has, a description YAML would misread, bad arguments: one line on stderr.

set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
KIT="$(cd "$HERE/.." && pwd)"
OUT="$KIT/skills"

refuse() { echo "gen-skills: REFUSED - $*" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --out) [ $# -ge 2 ] || refuse "--out has no value."; OUT="$2"; shift 2 ;;
    *) refuse "unknown argument '$1'." ;;
  esac
done

AGENTS="$KIT/AGENTS.md"; NEXTMD="$KIT/doctrine/NEXT.md"
[ -f "$AGENTS" ] || refuse "no AGENTS.md at $AGENTS."
[ -f "$NEXTMD" ] || refuse "no doctrine/NEXT.md at $NEXTMD."
GENLINE='<!-- generated by scripts/gen-skills.sh from AGENTS.md and doctrine/NEXT.md: do not edit -->'

# ------------------------------------------------------------------------------------------------ the skills, as data
# name | the phases whose gate it quotes ("-": none) | the NEXT.md rows it owns, in any order (<row>@<phase>: the row
# while `phase` is that one; "-": none) | the rows whose cell is quoted IN PART - up to its last sentence that ends
# within CUT bytes (<row>:<bytes>: within that many), then where the rest is - so that the skill stays under
# skills-check.sh's size limit; a choice written here, row by row, never made by the script ("-": none) |
# what it is, for the description ("-": its phases, from AGENTS.md section 3)
CUT=600
SKILLS='
hook-gauntlet           | -   | 1 3                      | -  | The entry to hook-gauntlet, the route that takes a Uniswap v4 hook from an idea to audit-ready (or tests an existing one hard) with its owner, on a local bench
hook-gauntlet-interview | 0   | 0 4@0                    | -  | -
hook-gauntlet-spec      | 1   | 4@1                      | -  | -
hook-gauntlet-battery   | 2 3 | 4b 5 6 6b 7 7b           | 5:120 6b | -
hook-gauntlet-round     | 4   | 2 8 9 10 11b 11 13 13b 14 | -  | -
hook-gauntlet-blackbox  | 5   | 12 15                    | -  | -
hook-gauntlet-release   | 6 7 | 16 17                    | -  | -
hook-gauntlet-dossier   | 8   | 9b 18 18b                | -  | -
hook-gauntlet-doctor    | -   | -                        | -  | The deterministic checks of hook-gauntlet, no model involved - what this machine lacks, whether the kit'"'"'s guards still go red, whether a STATE.md reads, whether the skills are as generated
'
# name | the work that should bring an agent to this skill, in plain words (no ": " - it goes into YAML as it is)
TRIGGERS='
hook-gauntlet           | starting or resuming work on a v4 hook'"'"'s route to audit-ready, a project with a .gauntlet/ directory, an owner asking to test an existing hook hard, or not knowing which hook-gauntlet skill comes next. Invoke it first
hook-gauntlet-interview | an owner bringing a new v4 hook idea, an existing hook with no tests and no history (phase 0 from the code), the owner interview, sizing the route (light or full) and agreeing a ceiling, or sketch mode while the design still moves
hook-gauntlet-spec      | writing or revising the falsifiable SPEC.md of a v4 hook, deciding each attack class, the hostile-actor table, the invariants in words
hook-gauntlet-battery   | writing Foundry tests for a v4 hook, the harness recipe (QUICKSTART 7b), running the battery, the long fuzz or a mutation, a fuzzer violation to turn into a test, the real pool manager'"'"'s bytecode, or any change to the bytecode
hook-gauntlet-round     | briefing an audit round, reading and triaging a round'"'"'s report, the invariant or action that would have caught a finding, a verifier pass, a round the environment stopped, the ceiling, or the loop'"'"'s exit
hook-gauntlet-blackbox  | the black-box round - a source-free bench, the spec'"'"'s promises attacked from outside
hook-gauntlet-release   | freezing a release candidate (promotion, a hash manifest, reproducible bytecode) or rehearsing a deployment runbook on a fork, simulated and never broadcast
hook-gauntlet-dossier   | writing the handoff dossier for human auditors, or its skeleton while findings wait on the owner - the end of the route
hook-gauntlet-doctor    | a machine you have not used, install-v4 / doctor, the selftest, next.sh refusing a STATE.md, a script'"'"'s verdict that looks wrong, or checking the skills
'
# name | entry or when | path from the kit's root | for entry: what to read it for ("-": AGENTS.md section 7's line);
# for when: the condition. Per skill, 2-5 files.
READS='
hook-gauntlet           | entry | state/README.md               | the flag block STATE.md carries, and what next.sh prints and refuses
hook-gauntlet           | when  | doctrine/RETROFIT.md          | the hook already exists, with tests or a history
hook-gauntlet           | when  | doctrine/UPSTREAM.md          | before phase 0: what a v4 hook can and cannot do, Uniswap'"'"'s own docs, the security framework
hook-gauntlet           | when  | AGENTS.md                     | a harness without skills (then read it in full)
hook-gauntlet-interview | entry | briefs/owner-interview.md     | the questions; fill the placeholders, do not rewrite the rules
hook-gauntlet-interview | entry | doctrine/COST.md              | -
hook-gauntlet-interview | when  | doctrine/RETROFIT.md          | the hook already exists and the owner wants it tested, not rebuilt
hook-gauntlet-interview | when  | doctrine/CHANGES.md           | the design is still moving (sketch mode, section 1)
hook-gauntlet-interview | when  | doctrine/UPSTREAM.md          | the security-framework self-score (section 2), and every protocol fact
hook-gauntlet-interview | when  | state/DECISIONS.md            | the shape of an entry, and the `source:` forms with the owner absent
hook-gauntlet-spec      | entry | briefs/spec-template.md       | the shape of SPEC.md; fill the placeholders, do not rewrite the rules
hook-gauntlet-spec      | entry | doctrine/HOOK-ATTACKS.md      | -
hook-gauntlet-spec      | when  | doctrine/V4-ACCOUNTING.md     | the hook moves value (takes, settles, holds tokens, returns deltas)
hook-gauntlet-spec      | when  | doctrine/INVARIANTS.md        | writing the invariants in words
hook-gauntlet-spec      | when  | doctrine/EVIDENCE.md          | a class you want to call "does not apply"
hook-gauntlet-spec      | when  | doctrine/FUZZ-ACTIONS.md      | the fuzz actions in words (the five questions)
hook-gauntlet-battery   | entry | doctrine/JUDGES.md            | the question each judge answers, and how each one lies
hook-gauntlet-battery   | entry | QUICKSTART.md                 | steps 7b (the harness) and 8 (one command per judge)
hook-gauntlet-round     | entry | doctrine/LOOP.md              | -
hook-gauntlet-round     | entry | briefs/audit-round.md         | the round'"'"'s brief; fill the placeholders, do not rewrite the rules
hook-gauntlet-round     | when  | doctrine/TRIAGE.md            | a finding to triage
hook-gauntlet-round     | when  | doctrine/VERIFY.md            | a report came back and you are about to act on it
hook-gauntlet-round     | when  | briefs/verifier.md            | a verifier pass (row 10)
hook-gauntlet-round     | when  | doctrine/SEVERITY.md          | rating a finding, or a round that argues one down
hook-gauntlet-round     | when  | doctrine/ORCHESTRATION.md     | models, benches, what the environment refuses, a stopped round
hook-gauntlet-blackbox  | entry | briefs/black-box.md           | the black-box brief; fill the placeholders, do not rewrite the rules
hook-gauntlet-blackbox  | when  | doctrine/ORCHESTRATION.md     | the harness or the provider stops the round (section 4)
hook-gauntlet-blackbox  | when  | doctrine/TRIAGE.md            | a divergence to fix in the code or in the spec
hook-gauntlet-blackbox  | when  | doctrine/VERIFY.md            | the report came back: reproduce each divergence before acting
hook-gauntlet-release   | entry | briefs/promotion.md           | the executor brief for phase 6, with its gates
hook-gauntlet-release   | when  | doctrine/CHANGES.md           | reopening a promoted revision (section 4)
hook-gauntlet-release   | when  | foundry-kit/v4/README.md      | the rehearsal needs the fork, the real manager or the address mining
hook-gauntlet-dossier   | entry | briefs/handoff-dossier.md     | the dossier'"'"'s template, every "must" section in order
hook-gauntlet-dossier   | entry | doctrine/EVIDENCE.md          | -
hook-gauntlet-dossier   | when  | doctrine/COST.md              | the ceiling, and whose it was (section 1)
hook-gauntlet-dossier   | when  | scripts/dossier-pdf.py        | the reading copy (PDF) of the dossier
hook-gauntlet-dossier   | when  | state/README.md               | the ROUND lines section 7 is assembled from
hook-gauntlet-doctor    | entry | QUICKSTART.md                 | steps 0 and 1: what you need, and proving the scripts before trusting them
hook-gauntlet-doctor    | when  | state/README.md               | next.sh refused a STATE.md, or named no row
hook-gauntlet-doctor    | when  | doctrine/JUDGES.md            | a verdict looks wrong (how each judge lies)
hook-gauntlet-doctor    | when  | skills/README.md              | the skills themselves: how they are made and installed
'
# the doctor's checks: scripts whose own first line (header line 3) is printed, in this order
DOCTOR_SCRIPTS='doctor.sh selftest.sh install-v4.sh next.sh skills-check.sh'
# the entry skill's four steps (Pedro Santana's): a label of this script's, then a sentence of AGENTS.md, quoted - each is
# checked to be in AGENTS.md (whitespace aside) before anything is written
STEPS='
A hook that already exists | An existing hook with tests or a history (audits, reports, a log) -> `doctrine/RETROFIT.md` after this file; without them -> phase 0, the code as the sketch to specify.
A new project | Before phase 0, install the state convention in the owner'"'"'s project: copy the three files from `state/` into `.gauntlet/` (the default; the project root also works - write which in `STATE.md`) and empty the examples, which describe a fictional hook
Resuming (`STATE.md`, `DECISIONS.md`, `LOG.md`) | Any agent that arrives with no context reads those three files and continues. If they disagree with the repository, the repository wins and you fix the files.
Where next | `scripts/next.sh <STATE.md>` computes it from the flags: it refuses a flag it cannot read, and names the row, or the rows that need your judgement first
'

# ------------------------------------------------------------------------------------------------ helpers
trim() { local s="$1"; s="${s#"${s%%[![:space:]]*}"}"; printf '%s' "${s%"${s##*[![:space:]]}"}"; }
squash() { printf '%s' "$1" | tr '\n\t' '  ' | tr -s ' '; }   # whitespace normalised, for "is this sentence there?"

# kitpaths <text>: inside every `...`, each word that names a file or directory of the kit gets the {{KIT}}/ prefix - a
# word with a "/" or a file extension, found at the kit's root (`scripts/battery.sh`, `QUICKSTART.md`, `state/`), or a
# bare *.md found under doctrine/ (NEXT.md writes `JUDGES.md` for doctrine/JUDGES.md). Anything else is left as it is:
# `STATE.md`, `pending/<id>.t.sol` and `.gauntlet/` are the project's, not the kit's.
BT='`'
KP_RE="^([^${BT}]*)${BT}([^${BT}]*)${BT}(.*)\$"
kitword() {
  local w="$1"
  if [[ $w =~ ^[A-Za-z0-9_][A-Za-z0-9._/-]*$ ]] && [[ $w == */* || $w =~ \.[a-z]+$ ]] && [ -e "$KIT/$w" ]; then
    printf '{{KIT}}/%s' "$w"
  elif [[ $w =~ ^[A-Za-z0-9_][A-Za-z0-9._-]*\.md$ ]] && [ -f "$KIT/doctrine/$w" ]; then
    printf '{{KIT}}/doctrine/%s' "$w"
  else
    printf '%s' "$w"
  fi
}
kitpaths() {
  local s="$1" out="" tok w sep
  while [[ $s =~ $KP_RE ]]; do
    out+="${BASH_REMATCH[1]}$BT"; tok="${BASH_REMATCH[2]}"; s="${BASH_REMATCH[3]}"
    sep=""
    while [[ $tok =~ ^([^ ]*)( +)(.*)$ ]]; do
      w="${BASH_REMATCH[1]}"; sep="${BASH_REMATCH[2]}"; tok="${BASH_REMATCH[3]}"
      out+="$(kitword "$w")$sep"
    done
    out+="$(kitword "$tok")$BT"
  done
  printf '%s' "$out$s"
}

# ------------------------------------------------------------------------------------------------ what the doctrine says
# the six rules: AGENTS.md between its markers, markers included, byte for byte
read -r nb ne lb le <<< "$(LC_ALL=C awk '
  /^<!-- invariants:begin -->[ \t\r]*$/ { nb++; if (nb == 1) lb = NR }
  /^<!-- invariants:end -->[ \t\r]*$/   { ne++; if (ne == 1) le = NR }
  END { printf "%d %d %d %d\n", nb + 0, ne + 0, lb + 0, le + 0 }' "$AGENTS")"
{ [ "$nb" = 1 ] && [ "$ne" = 1 ] && [ $((le - lb)) -ge 2 ]; } \
  || refuse "AGENTS.md has $nb '<!-- invariants:begin -->' and $ne '<!-- invariants:end -->' line(s): exactly one of each, begin first, the rules between them."
INVARIANTS="$(sed -n "${lb},${le}p" "$AGENTS")"

# NEXT.md's table: "id US action" per row, as next.sh reads it (every line of the table is a row of four cells)
declare -a TIDS=()
declare -A ACTION=()
while IFS=$'\037' read -r t_id t_act; do
  [ "$t_id" = BAD ] && refuse "doctrine/NEXT.md, line $t_act of the table is not a row of four cells."
  TIDS+=("$t_id"); ACTION[$t_id]="$t_act"
done < <(LC_ALL=C awk '
  { sub(/\r$/, "") }
  /^## / { intable = ($0 ~ /^## The table/); started = 0; ended = 0; next }
  !intable { next }
  !started && /^\|/ { started = 1 }
  !started { next }
  !ended && /^[ \t]*$/ { ended = 1; next }
  ended && !/^\|/ { next }
  {
    line = $0; n = gsub(/[|]/, "|", line)
    if ($0 ~ /^\|[-:| ]+$/ && n == 5) next
    split($0, c, /[|]/); id = c[2]; gsub(/^[ \t]+|[ \t]+$/, "", id)
    if ($0 !~ /^\|/ || n != 5 || id == "" || id ~ /[ \t]/) { print "BAD\037" NR; next }
    if (id == "#") next
    act = c[4]; gsub(/^[ \t]+|[ \t]+$/, "", act)
    print id "\037" act
  }' "$NEXTMD")
[ "${#TIDS[@]}" -gt 0 ] || refuse "doctrine/NEXT.md has no table under '## The table'."

# AGENTS.md section 3: phase -> name and gate cell; section 7: path -> its line
declare -A PNAME=() PGATE=() WHERE=()
while IFS=$'\037' read -r g_id g_name g_gate; do
  [ "$g_id" = BAD ] && refuse "AGENTS.md section 3, line $g_name: a phase row that is not four cells."
  PNAME[$g_id]="$g_name"; PGATE[$g_id]="$g_gate"
done < <(LC_ALL=C awk '
  { sub(/\r$/, "") }
  /^## / { in3 = ($0 ~ /^## 3\. /); next }
  in3 && /^\| [0-9] \|/ {
    line = $0; n = gsub(/[|]/, "|", line)
    if (n != 5) { print "BAD\037" NR; next }
    split($0, c, /[|]/)
    for (i = 2; i <= 5; i++) gsub(/^[ \t]+|[ \t]+$/, "", c[i])
    name = c[3]; gsub(/\*/, "", name)
    print c[2] "\037" name "\037" c[5]
  }' "$AGENTS")
while IFS=$'\037' read -r w_path w_line; do WHERE[$w_path]="$w_line"; done < <(LC_ALL=C awk '
  { sub(/\r$/, "") }
  /^## / { in7 = ($0 ~ /^## 7\. /); next }
  in7 && /^[a-z][A-Za-z0-9._\/-]* +[^ ]/ { p = $1; d = $0; sub(/^[^ ]+ +/, "", d); print p "\037" d }' "$AGENTS")

# ------------------------------------------------------------------------------------------------ the data, checked
declare -a NAMES=()
declare -A PHASES=() OWNS=() WHAT=() TRIG=() OWNER=() PART=()
while IFS='|' read -r s_name s_ph s_rows s_cut s_what; do
  s_name="$(trim "$s_name")"; [ -n "$s_name" ] || continue
  NAMES+=("$s_name"); PHASES[$s_name]="$(trim "$s_ph")"; OWNS[$s_name]="$(trim "$s_rows")"; WHAT[$s_name]="$(trim "$s_what")"
  PART[$s_name]="$(trim "$s_cut")"
done <<< "$SKILLS"
while IFS='|' read -r t_name t_text; do
  t_name="$(trim "$t_name")"; [ -n "$t_name" ] || continue; TRIG[$t_name]="$(trim "$t_text")"
done <<< "$TRIGGERS"
for s in "${NAMES[@]}"; do
  [ -n "${TRIG[$s]:-}" ] || refuse "skill $s has no trigger words (TRIGGERS)."
  for p in ${PHASES[$s]//-/}; do [ -n "${PGATE[$p]:-}" ] || refuse "skill $s quotes the gate of phase $p, which AGENTS.md section 3 does not have."; done
  for r in ${OWNS[$s]//-/}; do
    id="${r%@*}"
    [ -n "${ACTION[$id]+x}" ] || refuse "skill $s owns row $id, which doctrine/NEXT.md's table does not have."
    OWNER[$id]="${OWNER[$id]:-}${OWNER[$id]:+ }$s"
  done
done
for id in "${TIDS[@]}"; do
  [ -n "${OWNER[$id]:-}" ] || refuse "row $id of doctrine/NEXT.md's table is owned by no skill: give it one in gen-skills.sh (SKILLS)."
done
while IFS='|' read -r r k path note; do
  r="$(trim "$r")"; [ -n "$r" ] || continue
  [ -n "${PHASES[$r]+x}" ] || refuse "READS names a skill '$r' that SKILLS does not have."
  case "$(trim "$k")" in entry | when) ;; *) refuse "READS: '$(trim "$k")' for $r is neither entry nor when." ;; esac
  [ -n "$(trim "$path")" ] && [ -n "$(trim "$note")" ] || refuse "READS: a line for $r has no path or no note."
done <<< "$READS"
for t in "${!TRIG[@]}"; do [ -n "${PHASES[$t]+x}" ] || refuse "TRIGGERS names a skill '$t' that SKILLS does not have."; done
while IFS='|' read -r q_label q_text; do
  q_label="$(trim "$q_label")"; [ -n "$q_label" ] || continue; q_text="$(trim "$q_text")"
  case "$(squash "$(cat "$AGENTS")")" in
    *"$(squash "$q_text")"*) ;;
    *) refuse "the entry skill's step '$q_label' quotes a sentence AGENTS.md no longer has: '${q_text:0:80}...'." ;;
  esac
done <<< "$STEPS"

# partcell <cell> <bytes>: the cell up to its last sentence that ends within <bytes> (a ".", "?" or "!", a closing "**"
# or ")" after it, then a space); nothing when no sentence ends that early
partcell() {
  printf '%s\n' "$1" | LC_ALL=C awk -v max="$2" '{
    s = $0; n = 0; best = 0
    while (match(s, /[.?!](\*\*)?\)? /)) { n += RSTART + RLENGTH - 1; if (n - 1 <= max) best = n - 1; s = substr(s, RSTART + RLENGTH) }
    if (best > 0) print substr($0, 1, best) }'
}
for s in "${NAMES[@]}"; do
  for pc in ${PART[$s]//-/}; do
    id="${pc%%:*}"; lim="$CUT"; [ "$pc" = "$id" ] || lim="${pc#*:}"
    [[ $lim =~ ^[1-9][0-9]*$ ]] || refuse "skill $s quotes row $id in part within '$lim' bytes, which is not a number."
    case " ${OWNS[$s]} " in *" $id "*) ;; *) refuse "skill $s quotes row $id in part, and does not own it." ;; esac
    [ -n "$(partcell "${ACTION[$id]}" "$lim")" ] || refuse "row $id's cell has no sentence that ends within $lim bytes: skill $s cannot quote it in part."
  done
done

# rowlist <skill>: "4b, 5, 6" (a row@phase as "4 (phase 0)"), in the table's order
rowlist() {
  local s="$1" id r out=""
  for id in "${TIDS[@]}"; do
    for r in ${OWNS[$s]//-/}; do
      [ "${r%@*}" = "$id" ] || continue
      if [ "$r" != "$id" ]; then out+="${out:+, }$id (phase ${r#*@})"; else out+="${out:+, }$id"; fi
    done
  done
  printf '%s' "$out"
}
# phasewords <skill>: "phase 2 (Foundry sketch) and phase 3 (Battery)"
phasewords() {
  local p out="" n=0
  for p in ${PHASES[$1]}; do n=$((n + 1)); [ $n -gt 1 ] && out+=" and "; out+="phase $p (${PNAME[$p]})"; done
  printf '%s' "$out"
}

describe() {
  local s="$1" what rows d
  what="${WHAT[$s]}"
  [ "$what" = "-" ] && what="$(phasewords "$s" | sed 's/^p/P/') of hook-gauntlet, the route that takes a Uniswap v4 hook to audit-ready"
  rows="$(rowlist "$s")"
  case "$rows" in "") ;; *,*) what+="; doctrine/NEXT.md rows $rows" ;; *) what+="; doctrine/NEXT.md row $rows" ;; esac
  d="$what. Use for ${TRIG[$s]}."
  case "$d" in *': '* | *' #'* | *'"'* | *'`'*) refuse "the description of $s has ': ', ' #', a quote or a backtick, which YAML or the harness would misread." ;; esac
  [ "${#d}" -le 1024 ] || refuse "the description of $s is ${#d} characters, over the 1024 a harness reads."
  printf '%s' "$d"
}

# ------------------------------------------------------------------------------------------------ one SKILL.md
render() {
  local s="$1" p r id n label text line path kind note script pc lim
  printf -- '---\nname: %s\ndescription: %s\n---\n%s\n\n' "$s" "${DESC[$s]}" "$GENLINE"

  echo "## Rules that hold in every phase"
  echo
  printf '%s\n' "$INVARIANTS"
  echo
  echo 'Everything else is in `{{KIT}}/AGENTS.md`; where any file and it disagree, it wins.'
  echo

  if [ "$s" = hook-gauntlet ]; then
    echo "## This skill"
    echo
    n=0
    while IFS='|' read -r label text; do
      label="$(trim "$label")"; [ -n "$label" ] || continue; text="$(trim "$text")"; n=$((n + 1))
      case "$text" in *[.?!]) ;; *) text+="." ;; esac
      printf '%d. **%s.** %s\n' "$n" "$label" "$(kitpaths "$text")"
    done <<< "$STEPS"
    echo
  fi
  if [ "$s" = hook-gauntlet-doctor ]; then
    echo "## This skill"
    echo
    echo "No row of \`{{KIT}}/doctrine/NEXT.md\` is its own. The checks, each script's own first line:"
    echo
    for script in $DOCTOR_SCRIPTS; do
      line="$(sed -n 3p "$KIT/scripts/$script" | sed 's/^# *//')"
      [ -n "$line" ] || refuse "scripts/$script has no header line 3 for the doctor to quote."
      printf -- '- `{{KIT}}/scripts/%s` - %s\n' "$script" "${line#"$script" - }"
    done
    echo
  fi

  if [ "${OWNS[$s]}" != "-" ]; then
    if [ "$s" = hook-gauntlet ]; then echo "## The rows that stay with this skill"; else echo "## This phase"; fi
    echo
    echo "From \`{{KIT}}/doctrine/NEXT.md\`, the rows this skill owns and what each says to do:"
    echo
    for id in "${TIDS[@]}"; do
      for r in ${OWNS[$s]}; do
        [ "${r%@*}" = "$id" ] || continue
        if [ "$r" != "$id" ]; then label="Row $id, phase ${r#*@}"; else label="Row $id"; fi
        text="${ACTION[$id]}"
        for pc in ${PART[$s]//-/}; do
          [ "${pc%%:*}" = "$id" ] || continue
          lim="$CUT"; [ "$pc" = "$id" ] || lim="${pc#*:}"
          text="$(partcell "$text" "$lim") [...] (the rest: \`{{KIT}}/doctrine/NEXT.md\`, row $id)"
        done
        printf -- '- **%s** - %s\n' "$label" "$(kitpaths "$text")"
      done
    done
    echo
  fi

  if [ "${PHASES[$s]}" != "-" ]; then
    echo "## Gate (\`{{KIT}}/AGENTS.md\` section 3: all of it, measured)"
    echo
    for p in ${PHASES[$s]}; do printf -- '- **Phase %s, %s** - %s\n' "$p" "${PNAME[$p]}" "$(kitpaths "${PGATE[$p]}")"; done
    echo
  fi

  for kind in entry when; do   # a list with no item is left out, heading and all
    n=0
    while IFS='|' read -r r k path note; do
      [ "$(trim "$r")" = "$s" ] && [ "$(trim "$k")" = "$kind" ] || continue
      path="$(trim "$path")"; note="$(trim "$note")"; n=$((n + 1))
      if [ "$n" = 1 ]; then
        if [ "$kind" = entry ]; then printf '## Read on entry\n\n'; else printf '## Read when\n\n'; fi
      fi
      if [ "$kind" = entry ]; then
        [ "$note" = "-" ] && note="${WHERE[$path]:-}"
        if [ -n "$note" ]; then printf -- '- `{{KIT}}/%s` - %s\n' "$path" "$note"; else printf -- '- `{{KIT}}/%s`\n' "$path"; fi
      else
        printf -- '- %s: `{{KIT}}/%s`\n' "$note" "$path"
      fi
    done <<< "$READS"
    [ "$n" = 0 ] || echo
  done

  echo "## Done when"
  echo
  if [ "$s" = hook-gauntlet ]; then
    echo 'The row you took is closed and its flags are updated from outputs you read. Run `{{KIT}}/scripts/next.sh <STATE.md>` (default `.gauntlet/STATE.md`, then `./STATE.md`) and load the skill its row names:'
    echo
    echo "| NEXT.md row | skill |"
    echo "|---|---|"
    for n in "${NAMES[@]}"; do
      r="$(rowlist "$n")"; [ -n "$r" ] || r="none: next.sh refused, or the machine or the kit is not yet trusted"
      printf '| %s | `%s` |\n' "$r" "$n"
    done
  elif [ "${OWNS[$s]}" = "-" ]; then
    echo 'Run `{{KIT}}/scripts/next.sh <STATE.md>` and load the skill its row names (the table is in `hook-gauntlet`).'
  else
    echo 'The row is closed and its flags updated from outputs you read. Run `{{KIT}}/scripts/next.sh <STATE.md>` and load the skill its row names (the table is in `hook-gauntlet`).'
  fi
}

# ------------------------------------------------------------------------------------------------ write them
declare -A DESC=()
for s in "${NAMES[@]}"; do DESC[$s]="$(describe "$s")" || exit 2; done
mkdir -p "$OUT" || refuse "cannot create $OUT."
for s in "${NAMES[@]}"; do
  f="$OUT/$s/SKILL.md"
  if [ -e "$f" ] && ! grep -qxF "$GENLINE" "$f"; then
    refuse "$f is there and was not written by this script (no 'generated by' line): left alone."
  fi
done
TMPF="$(mktemp)"; trap 'rm -f "$TMPF"' EXIT
for s in "${NAMES[@]}"; do
  render "$s" > "$TMPF" || exit 2
  mkdir -p "$OUT/$s" || refuse "cannot create $OUT/$s."
  cat "$TMPF" > "$OUT/$s/SKILL.md" || refuse "cannot write $OUT/$s/SKILL.md."
  echo "wrote $s/SKILL.md ($(wc -c < "$OUT/$s/SKILL.md" | tr -d ' ') bytes, $(wc -l < "$OUT/$s/SKILL.md" | tr -d ' ') lines)"
done
echo "gen-skills: ${#NAMES[@]} skills written to $OUT"
