#!/usr/bin/env bash
#
# install-skills.sh - copy the kit's skills into a harness's skills directory, with `{{KIT}}` made a real path.
#
# The problem it solves: each harness reads skills from its own directory, and a skill names the kit's files by one
# prefix, `{{KIT}}`, that only the project knows: where the kit sits in it (a submodule or a copy - `lib/hook-gauntlet`
# is what the handoff dossier assumes) or, for a user-level install, the checkout's absolute path. So installing is:
# copy each skills/<name>/SKILL.md - that one file, nothing else of the kit - into <dest>/<name>/, with `{{KIT}}`
# replaced; then check that every path the installed skills name exists under the kit path, and say so when the kit is
# not there yet. Nothing is written until every destination has been checked: a <dest>/<name> that exists and is not
# one of this kit's skills (its SKILL.md has no "generated by scripts/gen-skills.sh" line) is refused, and never
# deleted; one of ours is replaced only with --force. A user-level directory is written only with --user.
#
# Adapted from Pedro Santana's install-skills.sh (his fork of this kit, 0xZ0uk/hook-gauntlet, 2026-09): the --harness
# and --project interface, the per-harness directories, the plan validated before anything is written, and the refusal
# to touch what is not the kit's are his. What changed: the skills are generated and thin, so only SKILL.md is copied
# (his copied each skill's whole tree, lib/ and out/ included), and the pointers are rewritten from one prefix instead of
# resolving relative to sibling skills. The directories, as his header recorded them (verified 2026-09-26 against each
# harness's documentation; not re-verified here, no network): Claude Code <project>/.claude/skills and ~/.claude/skills;
# Codex and the shared agents convention <project>/.agents/skills and ~/.agents/skills; Devin <project>/.devin/skills
# and ${XDG_CONFIG_HOME:-~/.config}/devin/skills.
#
# Usage:   scripts/install-skills.sh --harness claude|codex|devin|agents (--project DIR | --user) [--kit PATH]
#                                    [--force] [--dry-run]
#   --harness H    which harness's directory: claude -> .claude/skills, codex and agents -> .agents/skills,
#                  devin -> .devin/skills
#   --project DIR  install into DIR's project-level directory (DIR/.claude/skills, ...)
#   --user         install into the user-level directory instead (~/.claude/skills, ...); --kit must then be absolute
#   --kit PATH     what `{{KIT}}` becomes: a path relative to the project (default lib/hook-gauntlet), or absolute
#   --force        replace a <dest>/<name>/SKILL.md that this kit wrote before; anything else is refused all the same
#   --dry-run      say what would be written; write nothing
# Output:  "installed <name> -> <dest>/<name>/SKILL.md" per skill, then either "pointers: <k> resolve under <kit>" or
#          "pointers: NOT checked - no kit at <kit>: vendor it there (a submodule or a copy) ...", then
#          "installed: <n> skills into <dest>, {{KIT}} = <kit>"
# Exit:    0 installed (with the kit absent, said so); 1 installed, but the kit at <kit> lacks a path a skill names (a kit
#          of another version?) - each named; 2 REFUSED - bad arguments, the skills do not pass skills-check.sh, or a
#          destination that may not be replaced: one line on stderr, nothing written.

set -uo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
SRC="$(cd "$HERE/.." && pwd)/skills"
GENLINE='<!-- generated by scripts/gen-skills.sh from AGENTS.md and doctrine/NEXT.md: do not edit -->'
HARNESS="" PROJECT="" USERLEVEL=0 KITP="lib/hook-gauntlet" FORCE=0 DRY=0

refuse() { echo "install-skills: REFUSED - $*" >&2; exit 2; }

while [ $# -gt 0 ]; do
  case "$1" in
    --harness) [ $# -ge 2 ] || refuse "--harness has no value."; HARNESS="$2"; shift 2 ;;
    --project) [ $# -ge 2 ] || refuse "--project has no value."; PROJECT="$2"; shift 2 ;;
    --user) USERLEVEL=1; shift ;;
    --kit) [ $# -ge 2 ] || refuse "--kit has no value."; KITP="$2"; shift 2 ;;
    --force) FORCE=1; shift ;;
    --dry-run) DRY=1; shift ;;
    *) refuse "unknown argument '$1'." ;;
  esac
done

case "$HARNESS" in
  claude) SUB=".claude/skills" ;;
  codex | agents) SUB=".agents/skills" ;;
  devin) SUB=".devin/skills" ;;
  "") refuse "--harness is required: claude, codex, devin or agents." ;;
  *) refuse "--harness '$HARNESS' is not one of: claude, codex, devin, agents." ;;
esac
if [ -n "$PROJECT" ] && [ "$USERLEVEL" = 1 ]; then refuse "--project or --user, not both."; fi
if [ -z "$PROJECT" ] && [ "$USERLEVEL" = 0 ]; then
  refuse "say where: --project DIR (the project's own skills directory), or --user (a user-level directory, on purpose)."
fi
[[ $KITP =~ ^[A-Za-z0-9._/~+@-][A-Za-z0-9._/~+@\ -]*$ ]] || refuse "--kit '$KITP' has a character this installer does not write into a skill (letters, digits, . _ / ~ + @ - and spaces only)."
case "$KITP" in
  /*) ;;
  *) [ "$USERLEVEL" = 0 ] || refuse "--user needs an absolute --kit: a user-level skill is read from every project, and '$KITP' is relative to none." ;;
esac
KITP="${KITP%/}"

if [ "$USERLEVEL" = 1 ]; then
  case "$HARNESS" in
    devin) DEST="${XDG_CONFIG_HOME:-$HOME/.config}/devin/skills" ;;
    *) DEST="$HOME/$SUB" ;;
  esac
  KITABS="$KITP"
else
  [ -d "$PROJECT" ] || refuse "--project '$PROJECT' is not a directory."
  PROJECT="$(cd "$PROJECT" && pwd)"
  DEST="$PROJECT/$SUB"
  case "$KITP" in /*) KITABS="$KITP" ;; *) KITABS="$PROJECT/$KITP" ;; esac
fi

# the gate first: skills that are not what the doctrine generates today are not installed
[ -d "$SRC" ] || refuse "no skills/ beside this script's kit ($SRC)."
if ! "$HERE/skills-check.sh" > /dev/null 2>&1; then
  refuse "scripts/skills-check.sh does not pass on this kit's skills; not installing (run it to see why)."
fi

# the plan, checked before anything is written
names=()
for d in "$SRC"/*/; do
  [ -f "$d/SKILL.md" ] || continue
  n="$(basename "$d")"; t="$DEST/$n"
  if [ -e "$t" ]; then
    [ -d "$t" ] || refuse "$t exists and is not a directory - left alone."
    { [ -f "$t/SKILL.md" ] && grep -qxF "$GENLINE" "$t/SKILL.md"; } \
      || refuse "$t exists and is not one of this kit's skills (no SKILL.md with the 'generated by scripts/gen-skills.sh' line) - never replaced, never deleted."
    [ "$FORCE" = 1 ] || refuse "$t is this kit's, installed before - rerun with --force to replace it."
  fi
  names+=("$n")
done
[ "${#names[@]}" -gt 0 ] || refuse "no skill under $SRC."

if [ "$DRY" = 1 ]; then
  for n in "${names[@]}"; do echo "would write $DEST/$n/SKILL.md"; done
  echo "dry-run: ${#names[@]} skills into $DEST, {{KIT}} = $KITP"
  exit 0
fi

mkdir -p "$DEST" || refuse "cannot create $DEST."
for n in "${names[@]}"; do
  mkdir -p "$DEST/$n" || refuse "cannot create $DEST/$n."
  # a literal replacement, line by line: no sed, so nothing in the path is read as a pattern or a backreference
  while IFS= read -r line || [ -n "$line" ]; do
    printf '%s\n' "${line//"{{KIT}}"/"$KITP"}"
  done < "$SRC/$n/SKILL.md" > "$DEST/$n/SKILL.md" || refuse "cannot write $DEST/$n/SKILL.md."
  echo "installed $n -> $DEST/$n/SKILL.md"
done

# what was written is read back: no {{KIT}} left, and every path it names is under the kit - when the kit is there
rc=0 np=0
if grep -l '{{KIT}}' "$DEST"/*/SKILL.md > /dev/null 2>&1; then
  for n in "${names[@]}"; do grep -q '{{KIT}}' "$DEST/$n/SKILL.md" && echo "install-skills: $DEST/$n/SKILL.md still has {{KIT}}"; done
  rc=1
fi
if [ -d "$KITABS" ]; then
  for n in "${names[@]}"; do
    while IFS= read -r p; do
      np=$((np + 1))
      [ -e "$KITABS/$p" ] || { echo "install-skills: $n names $KITP/$p, which the kit at $KITABS does not have"; rc=1; }
    done < <(awk -v k="$KITP/" '{
        s = $0
        while ((i = index(s, k)) > 0) {
          s = substr(s, i + length(k)); p = s; sub(/[^A-Za-z0-9._\/-].*$/, "", p); sub(/[.]+$/, "", p)
          if (p != "") print p
        } }' "$DEST/$n/SKILL.md" | sort -u)
  done
  [ "$rc" = 0 ] && echo "pointers: $np resolve under $KITABS"
else
  echo "pointers: NOT checked - no kit at $KITABS: vendor it there (a submodule or a copy), or reinstall with --kit <where it is>; until then the skills name files that are not there"
fi
echo "installed: ${#names[@]} skills into $DEST, {{KIT}} = $KITP"
exit "$rc"
